### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "fghj@ru.ru",
  "password": "erytre"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/4

### Find all users with a given email
GET http://localhost:3000/auth?email=a@a.com


### Delete a user with a given id
DELETE http://localhost:3000/auth/545

### Update a user with a given id
PATCH http://localhost:3000/auth/4
content-type: application/json

{
    "password": "aaaaaa"
}
